# frozen_string_literal: true

source 'https://rubygems.org'

gem 'apstrings'
# This is listed as a dev dependency, but without it `require 'apstrings'`
# fails with:
#
# /$HOME/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/apstrings-0.4.1/lib/apstrings/logger.rb:3:in `require': cannot load such file -- colored (LoadError)
gem 'colored'
